### ISSUE TITLE
Tiles are missing when orientation changes after offline mode has been enabled

### ISSUE THREAD

**Issue by ryaa** [gregallensworth/L.TileLayer.Cordova#18]
This issue is somehow related to https://github.com/gregallensworth/L.TileLayer.Cordova/issues/17

There is one scenario when the map shown with some tiles missing after the offline mode has been enabled and then orientation changes in the cordova app.

Steps to reproduce:
1) initialise the map using this lib
2) change orientation to landscape/portrait
Note that the map is redrawn and all tiles are shown
3) save the map for offline mode (with workaround mentioned in https://github.com/gregallensworth/L.TileLayer.Cordova/issues/17)
4) open the map again
5) change orientation to landscape/portrait
Note that the map is redrawn and some tiles could be missing

Another variation is the same as above but disable connectivity after step 3, open the map in offline mode, then re-enable connectivity and re-open the map again and try to change orientation. The same problem.

I notices that this problem only happens after offline mode has been enabled. I also tried to use the original leaflet lib for online mode and this lib when offline enabled and once offline has been enabled the map may show tiles missing when orientation changes. If the app is restarted all works fine (in online mode or offline mode) until offline mode is enabled, after that the map shows missing tiles in online mode. 

If necessary i can provide the debuggable APK with the appropriate details to reproduce the problem.
Note that invalidateSize() or dropping the map container and re-creating it from scratch does not help. The problem still reproducible.

**Comment by gregallensworth** [comment]
Are you sure that the tiles were ever downloaded for the newly-revealed tiles when you change orientation? That is to say, are you sure that the missing tiles were within the bounding box you specified and thus got downloaded at all? If you change orientation, you could be bringing up new tiles which were not in your downloaded area.

Also, you're saying that if you go to offline mode, the map will fail to load tiles *even if you go back to online mode*?

Interesting, I'm not seeing this on our other apps which use L.TileLayer.Cordova though, so it must be something application-specific. If you send me a link to the APK, I'll see when I can get some free time to look at it.

**Comment by ryaa** [comment]
The tiles have been downloaded and saved for offline mode. When in offline mode and I change the orientation all works fine, all the tiles are fetch from the file system and shown fine. When in online mode everything also works fine, when i change orientation. However the problem appears exactly after a map has been saved for offline mode (and the app uses L.tileLayerCordova) and the app is in online.
 The cordova app for Android showing the problem with debug enabled can be found at https://www.dropbox.com/sh/lrcy1yrtb8ohkbv/AAB8ALTIKsp2txF-P2ypfpkOa?dl=0 There are several installers for different platforms.
Steps to reproduce the problem:
	1.	install the app
	2.	login as (you can skip first time launch tutorial) domain: first username: mobiledev@example.com password: 123123123
	3.	when on the main page (tickets list) click on the first ticket in the list
	4.	click on the 3rd tab to show the map
	5.	change orientation; note that the map is redrawn and all tiles are shown
	6.	return to ticket list
	7.	for the first ticket in the list please click on the right bottom cloud icon to add this ticket to offline mode This will save the ticket and all the related details into the offline storage. This includes saving the map for this ticket (note that the map is saved with padding workaround as suggested in https://github.com/gregallensworth/L.TileLayer.Cordova/issues/17)
	8.	when save is successfully complete (no errors shows and the cloud icon turns blue) click on the ticket to open it
	9.	in the ticket details click on the last/third tab to see the map with a polygon displayed Note that it displays fine
	10.	change orienation
	Note that some tiles on the right are missing. For this specific ticket there is a tiny grey are on the right however for others it could be as large as a half of the screen. When you try to pan the map the missing tiles are still there however zoom out/zoom in seems to help.

Another variation of the above scenario is after step 7 (when ticket is saved for offline mode) disable connectivity, open the ticket, then open the map, change orientation. Note that all works fine. Then change back to ticket list, enable connectivity, then open the ticket and the map. Now changing orientation shows the issue.
I noticed that the problem always appear after the ticket has been saved for offline mode and the app invokes L.tileLayerCordova. Otherwise the app works fine in online mode and shows all tiles when orientation changes.

Here are some tech details:
	1.	map tiles are saved for offline mode in /pages/ticket-list/ticket-list.ts in _downloadOfflineMap(ticketDetail: TicketDetail) method
	2.	map is loaded (in online or offline mode) in /pages/ticket-detail/ticket-detail-tab3.ts in loadMap() method Both of these methods uses you library.
	3.	when orientation changes in offline mode the app drops and re-creates the map. I also tried to do the same for online mode however the problem still reproducible.
	4.	I also tried to use invalidateSize() in online mode and it also made no difference. The problem is still reproducible

Note that this problem reproducible for many tickets. For some everything works fine, for some only tiny area is grey and tiles are missing and for some half of the screen shows missing tiles
Please let me know if you have any questions. The Skype is flaky on my end so I might not always be available online :(

Thank you very much!!!

**Comment by gregallensworth** [comment]
I can replicate the issue on Android, though when I unpack the `www` content and run it under Xcode, the screen never changes orientation at all. My tools for debugging on iOS are somewhat more detailed than for Android at the moment.

What I do see, is that `TicketDetailTab3Page.prototype.onResize()` destroys the map and then destroys the *mapContainer*DIV , then creates a new DIV and calls _loadMap() to create a new Map therein.

Normally I wouldn't do it that way, but would call `map.invalidateSize()` to have the map DIV resize, and remove/replace the GeoJSON vector feature, instead of destroying and re-creating the Map.

Looking at the code, each call to `loadMap()` re-creates the L.tileLayerCordova promises and re-calls `goOnline()` or `goOffline()`   It’s possible that Leaflet’s `remove()` is not cleaning up these layers and their resources as thoroughly as we would like (and/or on Android is not doing it as swiftly as is necessary to prevent some other race condition), and I "have a hunch" that this process of re-creating them instead of just resizing the map, is an opportunity to simplify the code a bit and eliminate some variables in this debugging process.

Initial thoughts on the events and responses:

* *ionViewDidLoad* -- do the L.Map() instantiation, add the layers, etc. and subscribe to `ticketDetailsViewDidLeaveAnnounced`
* *ticketDetailsViewDidLeaveAnnounced* -- a separate function to toggle the `_this.map.dragging.disable();` et cetera, when this value changes (rather than destroying and re-creating the Map each time)
* *ionViewDidEnter* -- call map.invalidateSize() so the map adjusts to the screen size, whether it has changed or not
* *onResize* -- call map.invalidateSize() and be done with it.

I apologize if it sounds like I'm micromanaging your code; that is not my intent. But if orientation change "did less" such as just calling a resize, we could more easily separate the L.tileLayerCordova behaviors from the resizing behaviors for improved debugging.

**Comment by ryaa** [comment]
Greg,

Thank you very much for your feedback...

I made the changes as you suggested but the problem is still reproducible.
Here are two versions:
1) this one is with invalidateSize method call (and without layer recreate) when onResize triggered - see https://www.dropbox.com/sh/iaie6ugh0zoygnt/AAA0YxF_QoOiyq8XwplIccUwa?dl=0
2) this one is with invalidateSize method call and layer recreated when onResize triggered - see https://www.dropbox.com/sh/kqgf9v3ke3d1vwv/AAB6D2SHhsS5wPTabTWRVmEGa?dl=0

Please note that in my implementation:
1) L.Map instantiation occurs not in ionViewDidLoad. The data to build the map is fetch from the server and not immediately available when ionViewDidLoad invoked. L.Map is invoked in the constructor
2) no thisis.map.dragging.disable() calls in ticketDetailsViewDidLeaveAnnounced. Not sure why this needs to be invoked there. When ticketDetailsViewDidLeaveAnnounced is called the view is destroyed. May be I'm missing smth?

So, as I mentioned, with the above changes the problem is still replicated on both Android and iOS. The map is redrawn fine on orientation change but after L.tileLayerCordova is invoked the map shows missing tiles after orientation change (even in online mode). Please note that with my initial implementation (with map destroy re-create) the map redrawn fine after adding to offline mode in offline mode only. Now, after the above changes, this shows missing tiles in both online and offline.

I think that it might be easier if I provide you everything so that you can run the app locally if you want to debug it using Xcode. Let me know if this works for you and where I can send you the link to download everything required to run the system locally.
